---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true 

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - unzip
      - python3 
      - python3-pip
    state: present
  become: true 
