services:
  api:
    build: ./api
    ports:
      - "4001:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    #volumes:
      #- ./api:/usr/src/app
      #- /usr/src/app/node_modules
    container_name: express-api

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    container_name: mongo-db
    volumes: 
      - ./mongo-data:/data/db # Maps to a folder on the host machine
